development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:8186b78d585ed9a386106a92e0b7ab7c@crestfish.redistogo.com:9390/
  channel_prefix: practica_production
